### ISSUE TITLE
Add endpoint to return state distribution and summary data for Title 1

### ISSUE THREAD

**Issue by sandeep-ps** [policy-design-lab/pdl-api#193]
We need a new endpoint that returns the state distribution of payment, acres, and payee counts at the title level for Title 1. This endpoint will be used to display the overall map within the Title 1 page. We need to add query parameters for passing start and end years.

**Comment by ywkim312** [comment]
I can work on this. Would you be able to give me the example output in here? Then I will try to create an endpoint

**Comment by sandeep-ps** [comment]
Thanks, @ywkim312. I will look into the formats and respond by noon today.
