### ISSUE TITLE
[FEATURE] Add house outlay to Title II endpoint

### ISSUE THREAD

**Issue by ylyangtw** [policy-design-lab/pdl-api#280]
There should be new endpoints for House Outlay max data. The format would be more like https://github.com/policy-design-lab/data-import/blob/develop/title-2-conservation/eqip_ira/eqip_ira_aggregated_prediction.json

Add endpoints:

GET /pdl/titles/title-ii/programs/house-outlay/predicted

**Comment by sandeep-ps** [comment]
We need to decide on the path. One option can be `/pdl/titles/title-ii/programs/house-outlay/predicted`.

**Comment by sandeep-ps** [comment]
Hi, Ya-Lan, I just realized you had put an endpoint path in the issue description. Please add `programs` to it to be consistent with other endpoints. Please see my comment above. Otherwise, the issue description looks good to me.
