### ISSUE TITLE
[TASK]Update Commodify I data

### ISSUE THREAD

**Issue by pengyin-shan** [policy-design-lab/pdl-api#64]
Hi @sandeep-ps and @ywkim312 , there are a few new data points that the Title I page will need (for JSON now and API in the near future):

1. Bases acres and Payee by state data for ARC-CO (other sub-program data will also be needed in the future, but we can do this later). The data file is https://uofi.app.box.com/file/1188038277911 and https://uofi.app.box.com/file/1201273113677. For now, we will need state-level data. It would be ideal if the format is similar to:

```
year: 2018-2022,
program: arcco,
data:
[
{
  state: Alabama,
  total_benefit:12345,
   payee: 12345, 
   enrolled_base: 12345
},
{
  state: Alaska,
  total_benefit: 12345,
   payee: 12345, 
   enrolled_base: 12345
},...
]
```
Please let me know if you want me to clarify more about this in a separate Zoom meeting.

2. Currently we don't have `totalPaymentInPercentageNationwide` data point for Commodity (data file: https://uofi.app.box.com/file/1183153793933). I wonder if we should consider adding it since EQIP have this data point, but I'd like to hear your thoughts.

Thank you!

**Comment by sandeep-ps** [comment]
Closing as completed by https://github.com/policy-design-lab/pdl-api/issues/99
