### ISSUE TITLE
Create endpoint for crop insurance

### ISSUE THREAD

**Issue by ywkim312** [policy-design-lab/pdl-api#78]
Create endpoints for crop insurance.

**Comment by sandeep-ps** [comment]
Suggesting some URLs for endpoints here:

GET /pdl/programs/crop-insurance/state-distribution
GET /pdl/programs/crop-insurance/summary

There are no subprograms for crop insurance. So I thought "summary" may be a better term.

**Comment by ywkim312** [comment]
> Suggesting some URLs for endpoints here:
> 
> GET /pdl/programs/crop-insurance/state-distribution GET /pdl/programs/crop-insurance/summary
> 
> There are no subprograms for crop insurance. So I thought "summary" may be a better term.

sounds good!
